// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: Inference.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request from ingest worker / Go client
type FrameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FrameData     []byte                 `protobuf:"bytes,1,opt,name=frame_data,json=frameData,proto3" json:"frame_data,omitempty"` // raw RGB bytes
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`                         // frame width
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`                       // frame height
	Channels      int32                  `protobuf:"varint,4,opt,name=channels,proto3" json:"channels,omitempty"`                   // MUST be 3 (RGB)
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                 // client timestamp
	FrameId       string                 `protobuf:"bytes,6,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`       // unique frame identifier
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameRequest) Reset() {
	*x = FrameRequest{}
	mi := &file_Inference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameRequest) ProtoMessage() {}

func (x *FrameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Inference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameRequest.ProtoReflect.Descriptor instead.
func (*FrameRequest) Descriptor() ([]byte, []int) {
	return file_Inference_proto_rawDescGZIP(), []int{0}
}

func (x *FrameRequest) GetFrameData() []byte {
	if x != nil {
		return x.FrameData
	}
	return nil
}

func (x *FrameRequest) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *FrameRequest) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *FrameRequest) GetChannels() int32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

func (x *FrameRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *FrameRequest) GetFrameId() string {
	if x != nil {
		return x.FrameId
	}
	return ""
}

// Single face bounding box
type BoundingBox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	Confidence    float32                `protobuf:"fixed32,5,opt,name=confidence,proto3" json:"confidence,omitempty"` // detection confidence (0.0 - 1.0)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoundingBox) Reset() {
	*x = BoundingBox{}
	mi := &file_Inference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoundingBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundingBox) ProtoMessage() {}

func (x *BoundingBox) ProtoReflect() protoreflect.Message {
	mi := &file_Inference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundingBox.ProtoReflect.Descriptor instead.
func (*BoundingBox) Descriptor() ([]byte, []int) {
	return file_Inference_proto_rawDescGZIP(), []int{1}
}

func (x *BoundingBox) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *BoundingBox) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *BoundingBox) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *BoundingBox) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BoundingBox) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

// Response with all detected faces
type DetectionResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Faces            []*BoundingBox         `protobuf:"bytes,1,rep,name=faces,proto3" json:"faces,omitempty"`
	Timestamp        int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                         // echo client timestamp
	FrameId          string                 `protobuf:"bytes,3,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`                               // echo client frame_id
	ProcessingTimeMs int64                  `protobuf:"varint,4,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"` // server processing time
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DetectionResponse) Reset() {
	*x = DetectionResponse{}
	mi := &file_Inference_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionResponse) ProtoMessage() {}

func (x *DetectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Inference_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectionResponse.ProtoReflect.Descriptor instead.
func (*DetectionResponse) Descriptor() ([]byte, []int) {
	return file_Inference_proto_rawDescGZIP(), []int{2}
}

func (x *DetectionResponse) GetFaces() []*BoundingBox {
	if x != nil {
		return x.Faces
	}
	return nil
}

func (x *DetectionResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DetectionResponse) GetFrameId() string {
	if x != nil {
		return x.FrameId
	}
	return ""
}

func (x *DetectionResponse) GetProcessingTimeMs() int64 {
	if x != nil {
		return x.ProcessingTimeMs
	}
	return 0
}

var File_Inference_proto protoreflect.FileDescriptor

const file_Inference_proto_rawDesc = "" +
	"\n" +
	"\x0fInference.proto\x12\tinference\"\xb0\x01\n" +
	"\fFrameRequest\x12\x1d\n" +
	"\n" +
	"frame_data\x18\x01 \x01(\fR\tframeData\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12\x1a\n" +
	"\bchannels\x18\x04 \x01(\x05R\bchannels\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x19\n" +
	"\bframe_id\x18\x06 \x01(\tR\aframeId\"w\n" +
	"\vBoundingBox\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x02R\n" +
	"confidence\"\xa8\x01\n" +
	"\x11DetectionResponse\x12,\n" +
	"\x05faces\x18\x01 \x03(\v2\x16.inference.BoundingBoxR\x05faces\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x19\n" +
	"\bframe_id\x18\x03 \x01(\tR\aframeId\x12,\n" +
	"\x12processing_time_ms\x18\x04 \x01(\x03R\x10processingTimeMs2U\n" +
	"\rFaceDetection\x12D\n" +
	"\vDetectFaces\x12\x17.inference.FrameRequest\x1a\x1c.inference.DetectionResponseB\"Z webrtc-pion-face-engine/proto;pbb\x06proto3"

var (
	file_Inference_proto_rawDescOnce sync.Once
	file_Inference_proto_rawDescData []byte
)

func file_Inference_proto_rawDescGZIP() []byte {
	file_Inference_proto_rawDescOnce.Do(func() {
		file_Inference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Inference_proto_rawDesc), len(file_Inference_proto_rawDesc)))
	})
	return file_Inference_proto_rawDescData
}

var file_Inference_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_Inference_proto_goTypes = []any{
	(*FrameRequest)(nil),      // 0: inference.FrameRequest
	(*BoundingBox)(nil),       // 1: inference.BoundingBox
	(*DetectionResponse)(nil), // 2: inference.DetectionResponse
}
var file_Inference_proto_depIdxs = []int32{
	1, // 0: inference.DetectionResponse.faces:type_name -> inference.BoundingBox
	0, // 1: inference.FaceDetection.DetectFaces:input_type -> inference.FrameRequest
	2, // 2: inference.FaceDetection.DetectFaces:output_type -> inference.DetectionResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_Inference_proto_init() }
func file_Inference_proto_init() {
	if File_Inference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Inference_proto_rawDesc), len(file_Inference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Inference_proto_goTypes,
		DependencyIndexes: file_Inference_proto_depIdxs,
		MessageInfos:      file_Inference_proto_msgTypes,
	}.Build()
	File_Inference_proto = out.File
	file_Inference_proto_goTypes = nil
	file_Inference_proto_depIdxs = nil
}
