// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: inference.proto
#ifndef GRPC_inference_2eproto__INCLUDED
#define GRPC_inference_2eproto__INCLUDED

#include "inference.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace inference {

class FaceDetection final {
 public:
  static constexpr char const* service_full_name() {
    return "inference.FaceDetection";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status DetectFaces(::grpc::ClientContext* context, const ::inference::FrameRequest& request, ::inference::DetectionResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::inference::DetectionResponse>> AsyncDetectFaces(::grpc::ClientContext* context, const ::inference::FrameRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::inference::DetectionResponse>>(AsyncDetectFacesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::inference::DetectionResponse>> PrepareAsyncDetectFaces(::grpc::ClientContext* context, const ::inference::FrameRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::inference::DetectionResponse>>(PrepareAsyncDetectFacesRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void DetectFaces(::grpc::ClientContext* context, const ::inference::FrameRequest* request, ::inference::DetectionResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void DetectFaces(::grpc::ClientContext* context, const ::inference::FrameRequest* request, ::inference::DetectionResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::inference::DetectionResponse>* AsyncDetectFacesRaw(::grpc::ClientContext* context, const ::inference::FrameRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::inference::DetectionResponse>* PrepareAsyncDetectFacesRaw(::grpc::ClientContext* context, const ::inference::FrameRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status DetectFaces(::grpc::ClientContext* context, const ::inference::FrameRequest& request, ::inference::DetectionResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::inference::DetectionResponse>> AsyncDetectFaces(::grpc::ClientContext* context, const ::inference::FrameRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::inference::DetectionResponse>>(AsyncDetectFacesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::inference::DetectionResponse>> PrepareAsyncDetectFaces(::grpc::ClientContext* context, const ::inference::FrameRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::inference::DetectionResponse>>(PrepareAsyncDetectFacesRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void DetectFaces(::grpc::ClientContext* context, const ::inference::FrameRequest* request, ::inference::DetectionResponse* response, std::function<void(::grpc::Status)>) override;
      void DetectFaces(::grpc::ClientContext* context, const ::inference::FrameRequest* request, ::inference::DetectionResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::inference::DetectionResponse>* AsyncDetectFacesRaw(::grpc::ClientContext* context, const ::inference::FrameRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::inference::DetectionResponse>* PrepareAsyncDetectFacesRaw(::grpc::ClientContext* context, const ::inference::FrameRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_DetectFaces_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status DetectFaces(::grpc::ServerContext* context, const ::inference::FrameRequest* request, ::inference::DetectionResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_DetectFaces : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DetectFaces() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_DetectFaces() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DetectFaces(::grpc::ServerContext* /*context*/, const ::inference::FrameRequest* /*request*/, ::inference::DetectionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDetectFaces(::grpc::ServerContext* context, ::inference::FrameRequest* request, ::grpc::ServerAsyncResponseWriter< ::inference::DetectionResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_DetectFaces<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_DetectFaces : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_DetectFaces() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::inference::FrameRequest, ::inference::DetectionResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::inference::FrameRequest* request, ::inference::DetectionResponse* response) { return this->DetectFaces(context, request, response); }));}
    void SetMessageAllocatorFor_DetectFaces(
        ::grpc::MessageAllocator< ::inference::FrameRequest, ::inference::DetectionResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::inference::FrameRequest, ::inference::DetectionResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_DetectFaces() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DetectFaces(::grpc::ServerContext* /*context*/, const ::inference::FrameRequest* /*request*/, ::inference::DetectionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DetectFaces(
      ::grpc::CallbackServerContext* /*context*/, const ::inference::FrameRequest* /*request*/, ::inference::DetectionResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_DetectFaces<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_DetectFaces : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DetectFaces() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_DetectFaces() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DetectFaces(::grpc::ServerContext* /*context*/, const ::inference::FrameRequest* /*request*/, ::inference::DetectionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_DetectFaces : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DetectFaces() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_DetectFaces() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DetectFaces(::grpc::ServerContext* /*context*/, const ::inference::FrameRequest* /*request*/, ::inference::DetectionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDetectFaces(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_DetectFaces : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_DetectFaces() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->DetectFaces(context, request, response); }));
    }
    ~WithRawCallbackMethod_DetectFaces() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DetectFaces(::grpc::ServerContext* /*context*/, const ::inference::FrameRequest* /*request*/, ::inference::DetectionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DetectFaces(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_DetectFaces : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_DetectFaces() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::inference::FrameRequest, ::inference::DetectionResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::inference::FrameRequest, ::inference::DetectionResponse>* streamer) {
                       return this->StreamedDetectFaces(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_DetectFaces() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DetectFaces(::grpc::ServerContext* /*context*/, const ::inference::FrameRequest* /*request*/, ::inference::DetectionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDetectFaces(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::inference::FrameRequest,::inference::DetectionResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_DetectFaces<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_DetectFaces<Service > StreamedService;
};

}  // namespace inference


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_inference_2eproto__INCLUDED
